services:
  mongodb:
    image: mongo:latest
    container_name: pixelboard-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: pixelboard
    volumes:
      - mongo-data:/data/db
      - ./packages/mongo-init:/docker-entrypoint-initdb.d  

volumes:
  mongo-data:
    driver: local
